import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MediaPlaceholder } from "@/components/media-placeholder";
import { StandardCta } from "@/components/page-templates";
import { findPost, posts } from "@/content/site-data";

export function generateStaticParams() { return posts.map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: PageProps<"/blog/[slug]">): Promise<Metadata> { const { slug } = await params; const post = findPost(slug); return post ? { title: post.title, description: post.excerpt } : {}; }
export default async function ArticlePage({ params }: PageProps<"/blog/[slug]">) { const { slug } = await params; const post = findPost(slug); if (!post) notFound(); return <main id="top"><article><header className="page-hero page-hero--yellow"><div className="container article-header"><p className="eyebrow">{post.category}</p><h1>{post.title}</h1><p className="page-hero__lead">{post.excerpt}</p><div className="article-meta"><span>{post.date}</span><span>{post.readTime}</span><span>Yellow Strategy Team</span></div></div></header><div className="section"><div className="container article-body"><MediaPlaceholder label={`${post.title} feature image placeholder`} /><p className="large-copy">Sustainable growth rarely comes from a single clever tactic. It comes from making a few high-value decisions clearly, then connecting the work around them.</p><p>This editorial page demonstrates the complete article structure for Yellow Agency. Replace this placeholder body with the approved article while preserving the heading hierarchy, reading width, related links, and media positions.</p><h2>Start with the customer decision</h2><p>Before choosing a channel or format, understand the decision a customer is trying to make. Useful marketing reduces uncertainty, makes the value concrete, and gives people a natural next step.</p><div className="article-callout">The strongest marketing systems make the right action feel obvious—not forced.</div><h2>Connect the message to the experience</h2><p>A compelling campaign cannot compensate for a confusing landing page or slow follow-up. Carry the same promise, proof, and tone through every touchpoint so the customer experiences one coherent story.</p><h2>Measure what changes a decision</h2><p>Good reporting helps a team decide what to do next. Focus on meaningful movement, document what changed, and use that evidence to improve the next cycle.</p><Link href="/contact-us" className="text-link">Discuss this with our team <span>↗</span></Link></div></div></article><StandardCta title="Ready to turn useful thinking into useful growth?" /></main>; }
